"""Live manuscripts are produced by the pinned official PaperOrchestra agents."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from .contracts import AgentOutput, RunState
from .paper_orchestra import run_official_writer

if TYPE_CHECKING:
    from .config import ResearchConfig
    from .store import Store


def compose_manuscript(
    state: RunState, *, store: Store, config: ResearchConfig
) -> tuple[AgentOutput, list[dict[str, Any]]]:
    from .model_inventory import guard_writer_models

    guard_writer_models(config)
    manuscript, references = run_official_writer(state, store, config)
    return AgentOutput(
        summary="Manuscript generated by pinned official PaperOrchestra; source, PDF and execution bundle archived.",
        manuscript=manuscript,
        evidence_ids=[e["id"] for e in references],
    ), references
